### ISSUE TITLE
Uncaught TypeError: Failed to execute 'importNode' on 'Document': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by sysmat** [xhofe/solid-iconify#1]
- dep:

```json
"devDependencies": {
    "@iconify-icon/solid": "^1.0.7",
    "@iconify/json": "^2.2.42",
    "@solidjs/testing-library": "^0.7.0",
    "@testing-library/user-event": "^14.4.3",
    "@vitest/coverage-c8": "^0.29.8",
    "autoprefixer": "^10.4.14",
    "jsdom": "^21.1.1",
    "postcss": "^8.4.21",
    "tailwindcss": "^3.3.0",
    "turbo": "^1.8.8",
    "typescript": "^5.0.2",
    "vite": "^4.2.1",
    "vite-plugin-solid": "2.6.1",
    "vitest": "^0.29.8"
  },
  "dependencies": {
    "@felte/solid": "^1.2.7",
    "@solid-primitives/clipboard": "^1.5.3",
    "@solid-primitives/connectivity": "^0.3.11",
    "@solid-primitives/geolocation": "^1.4.7",
    "@solid-primitives/keyboard": "^1.0.11",
    "@solidjs/router": "^0.8.2",
    "daisyui": "^2.51.5",
    "hotkeys-js": "^3.10.1",
    "ky": "^0.33.3",
    "radash": "^10.8.1",
    "solid-js": "^1.7.0",
    "zod": "^3.21.4"
  }
```

- error stack browser console

```
Uncaught TypeError: Failed to execute 'importNode' on 'Document': parameter 1 is not of type 'Node'.
    at iconify.jsx:15:5
    at untrack (dev.js:430:33)
    at iconify.jsx:15:5
    at Icon (iconify.jsx:16:208)
    at dev.js:548:12
    at untrack (dev.js:434:12)
    at Object.fn (dev.js:544:37)
    at runComputation (dev.js:695:22)
    at updateComputation (dev.js:678:3)
    at devComponent (dev.js:555:3)
```

**Comment by sysmat** [comment]
- when upgrading error happened
```
@iconify/json  ^2.2.41  →  ^2.2.42
 solid-js       ^1.6.16  →   ^1.7.0
```

**Comment by xhofe** [comment]
It seems you have come to the wrong repository.
This repo is not the source code of `@iconify-icon/solid`, you should go to https://github.com/iconify/iconify/tree/main/iconify-icon/solid

**Comment by sysmat** [comment]
my mistake, sorry
